# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Mod properties
mod.version=0.0.1
mod.group=space.anatomyuniverse
mod.id=musavacca
mod.name=Musavacca

publish.modrinth=# Modrinth mod slug
publish.curseforge=# Curseforge numeric mod ID
