license = "LGPL-3.0-only"

modLoader = "javafml"
loaderVersion = "[1,)"

[[mixins]]
config = "musavacca.mixins.json"

[[mods]]
modId = "${id}"
displayName = "${name}"
version = "${version}"
authors = "AnatomyKing"
description = "Banana Cows."

logoFile = "assets/${id}/icon.png"

#displayURL = "..."
#issueTrackerUrl = "..."

[[dependencies."${id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft}"
ordering = "NONE"
side = "BOTH"

${compat_dependencies}