deps.neoforge=21.1.251

# Mod compatibility dependencies
compat.mods=gleam neapolitan

# Gleam
compat.gleam.maven=maven.modrinth:3vnBzYeg:zCkCyEZR
compat.gleam.version_range=[1.1.0.0]
compat.gleam.side=CLIENT
compat.gleam.ordering=AFTER

compat.gleam.modrinth_project=3vnBzYeg
compat.gleam.curseforge_slug=gleam

# Neapolitan
compat.neapolitan.maven=maven.modrinth:InYMuiQt:RQ5qgaUC
compat.neapolitan.version_range=[6.0.0,)
compat.neapolitan.side=BOTH
compat.neapolitan.ordering=AFTER

compat.neapolitan.modrinth_project=InYMuiQt
compat.neapolitan.curseforge_slug=neapolitan

# Neapolitan development/runtime dependencies
compat.neapolitan.runtime_mavens=com.teamabnormals:blueprint:1.21.1-8.0.8 com.teamabnormals:gallery:1.21.1-2.0.0

# Minecraft dependency for neoforge.mods.toml
mod.mc_dep=[1.21.1]

# Release title
mod.mc_title=1.21.1

# Publishing targets
mod.mc_targets=1.21.1